"""
GitHub Issue Creator — takes the final scoped feature spec and creates
a well-formatted GitHub issue with all the context from the scoping conversation.
"""

import os
from typing import Optional

from github import Github, GithubException

import config


def create_issue(
    feature_spec: dict,
    client_id: str,
    conversation_summary: str = "",
    prototype_choice: str = "",
) -> Optional[str]:
    """
    Create a GitHub issue from the scoped feature spec.
    Returns the issue URL or None if creation fails.
    """
    if not config.GITHUB_TOKEN or not config.GITHUB_REPO:
        # Demo mode: return a fake URL
        return _format_issue_preview(feature_spec, client_id, conversation_summary, prototype_choice)

    gh = Github(config.GITHUB_TOKEN)
    repo = gh.get_repo(config.GITHUB_REPO)

    title = feature_spec.get("title", "Untitled Feature Request")
    body = _build_issue_body(feature_spec, client_id, conversation_summary, prototype_choice)
    labels = _get_labels(feature_spec)

    try:
        issue = repo.create_issue(
            title=f"[Client Request] {title}",
            body=body,
            labels=labels,
        )
        return issue.html_url
    except GithubException as e:
        print(f"GitHub issue creation failed: {e}")
        return None


def _build_issue_body(
    spec: dict,
    client_id: str,
    conversation_summary: str,
    prototype_choice: str,
) -> str:
    """Build the markdown body for the GitHub issue."""
    requirements = spec.get("requirements", [])
    out_of_scope = spec.get("out_of_scope", [])
    preferences = spec.get("client_preferences", [])

    body = f"""## Feature Request — Client Scoped

**Client:** {client_id}
**Target Component:** {spec.get('target_component', 'TBD')}
**Complexity:** {spec.get('complexity_estimate', 'unknown')}
**Prototype Approved:** {prototype_choice or 'N/A'}

---

### Description

{spec.get('description', 'No description provided.')}

### Requirements

{chr(10).join(f'- [ ] {r}' for r in requirements)}

### Out of Scope

{chr(10).join(f'- {item}' for item in out_of_scope)}

### Client Preferences

{chr(10).join(f'- {p}' for p in preferences)}

---

### Scoping Context

{conversation_summary or '_No conversation summary available._'}

---

> This issue was auto-generated by the Scope Agent from a client conversation.
> The client reviewed and approved the prototype before this issue was created.
"""
    return body


def _get_labels(spec: dict) -> list[str]:
    """Determine labels based on the feature spec."""
    labels = ["client-request", "scoped"]
    complexity = spec.get("complexity_estimate", "")
    if complexity:
        labels.append(f"complexity:{complexity}")
    return labels


def _format_issue_preview(
    spec: dict,
    client_id: str,
    conversation_summary: str,
    prototype_choice: str,
) -> str:
    """
    In demo mode (no GitHub token), return a formatted preview of what
    the issue would look like.
    """
    body = _build_issue_body(spec, client_id, conversation_summary, prototype_choice)
    title = spec.get("title", "Untitled Feature Request")
    return f"[DEMO] Issue would be created:\n\nTitle: [Client Request] {title}\n\n{body}"
